environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install cx_Freeze discord.py irc3"

build_script:
  - "python setup.py build_ext --inplace"

test_script:
  # Run the project tests
  # - "python tests/test_tgen.py"

after_test:
  # If tests are successful, create binary packages for the project.
  - "cd standalone"
  - "call build.bat"
  - "echo %APPVEYOR_JOB_NAME%"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: standalone\cuwo.zip

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#